"""empty message

Revision ID: 053b22a52472
Revises: e30701004a5e
Create Date: 2020-01-04 12:03:38.017345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '053b22a52472'
down_revision = 'e30701004a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_alarm_info', sa.Column('alarm_address', sa.String(length=150), nullable=True))
    op.add_column('tb_alarm_info', sa.Column('alarm_level', sa.String(length=3), nullable=True))
    op.add_column('tb_alarm_info', sa.Column('alarm_type', sa.String(length=6), nullable=True))
    op.add_column('tb_alarm_info', sa.Column('img_base64', sa.TEXT(), nullable=True))
    op.add_column('tb_alarm_info', sa.Column('img_name', sa.String(length=60), nullable=True))
    op.add_column('tb_alarm_info', sa.Column('img_remark', sa.String(length=1500), nullable=True))
    op.add_column('tb_alarm_info', sa.Column('img_url', sa.String(length=600), nullable=True))
    op.add_column('tb_alarm_info', sa.Column('link_obj', sa.String(length=60), nullable=True))
    op.add_column('tb_alarm_info', sa.Column('video_url', sa.String(length=600), nullable=True))
    op.drop_column('tb_alarm_info', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_alarm_info', sa.Column('image', mysql.TEXT(), nullable=True))
    op.drop_column('tb_alarm_info', 'video_url')
    op.drop_column('tb_alarm_info', 'link_obj')
    op.drop_column('tb_alarm_info', 'img_url')
    op.drop_column('tb_alarm_info', 'img_remark')
    op.drop_column('tb_alarm_info', 'img_name')
    op.drop_column('tb_alarm_info', 'img_base64')
    op.drop_column('tb_alarm_info', 'alarm_type')
    op.drop_column('tb_alarm_info', 'alarm_level')
    op.drop_column('tb_alarm_info', 'alarm_address')
    # ### end Alembic commands ###
