"""empty message

Revision ID: 2b3d9541972a
Revises: 6209f3f27855
Create Date: 2020-01-14 13:31:52.851903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3d9541972a'
down_revision = '6209f3f27855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_permission', sa.Column('type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_permission', 'type')
    # ### end Alembic commands ###
