"""empty message

Revision ID: 6209f3f27855
Revises: dc34eeb712cd
Create Date: 2020-01-10 16:32:16.222663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6209f3f27855'
down_revision = 'dc34eeb712cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_permission',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('pname', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('describe', sa.String(length=1500), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('tb_role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['tb_permission.pid'], ),
    sa.ForeignKeyConstraint(['rid'], ['tb_role.rid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tb_role_limit')
    op.drop_index('limit', table_name='tb_limit')
    op.drop_table('tb_limit')
    op.add_column('tb_role', sa.Column('describe', sa.String(length=50), nullable=True))
    op.add_column('tb_role', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('tb_role', sa.Column('state', sa.String(length=50), nullable=True))
    op.drop_index('role', table_name='tb_role')
    op.create_unique_constraint(None, 'tb_role', ['name'])
    op.drop_column('tb_role', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_role', sa.Column('role', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'tb_role', type_='unique')
    op.create_index('role', 'tb_role', ['role'], unique=True)
    op.drop_column('tb_role', 'state')
    op.drop_column('tb_role', 'name')
    op.drop_column('tb_role', 'describe')
    op.create_table('tb_limit',
    sa.Column('lid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('lid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('limit', 'tb_limit', ['limit'], unique=True)
    op.create_table('tb_role_limit',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('rid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('lid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lid'], ['tb_limit.lid'], name='tb_role_limit_ibfk_1'),
    sa.ForeignKeyConstraint(['rid'], ['tb_role.rid'], name='tb_role_limit_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('tb_role_permission')
    op.drop_table('tb_permission')
    # ### end Alembic commands ###
