"""empty message

Revision ID: 9c402b6a7b9c
Revises: da5c1c869884
Create Date: 2020-01-07 15:14:41.215370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c402b6a7b9c'
down_revision = 'da5c1c869884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_camera_id', table_name='tb_camera')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_camera_id', 'tb_camera', ['unique_camera_id'], unique=True)
    # ### end Alembic commands ###
