"""empty message

Revision ID: da5c1c869884
Revises: 68d308c922b4
Create Date: 2020-01-07 15:01:57.109330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da5c1c869884'
down_revision = '68d308c922b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_camera', sa.Column('device_no_', sa.String(length=50), nullable=True))
    op.drop_column('tb_camera', 'device_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_camera', sa.Column('device_no', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('tb_camera', 'device_no_')
    # ### end Alembic commands ###
