"""empty message

Revision ID: dc34eeb712cd
Revises: 9c402b6a7b9c
Create Date: 2020-01-08 10:05:43.911690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc34eeb712cd'
down_revision = '9c402b6a7b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_camera', sa.Column('device_no', sa.String(length=50), nullable=True))
    op.drop_column('tb_camera', 'device_no_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_camera', sa.Column('device_no_', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('tb_camera', 'device_no')
    # ### end Alembic commands ###
