"""empty message

Revision ID: e30701004a5e
Revises: 
Create Date: 2020-01-03 18:51:30.213751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30701004a5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_limit',
    sa.Column('lid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('lid'),
    sa.UniqueConstraint('limit')
    )
    op.create_table('tb_role',
    sa.Column('rid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('rid'),
    sa.UniqueConstraint('role')
    )
    op.create_table('tb_server',
    sa.Column('unique_server_id', sa.String(length=50), nullable=False),
    sa.Column('server_name', sa.String(length=50), nullable=True),
    sa.Column('server_ip', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=50), nullable=True),
    sa.Column('server_state', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('unique_server_id')
    )
    op.create_table('tb_user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uname', sa.String(length=50), nullable=False),
    sa.Column('sex', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=50), nullable=False),
    sa.Column('pwd', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('account')
    )
    op.create_table('tb_camera',
    sa.Column('unique_camera_id', sa.String(length=50), nullable=False),
    sa.Column('camera_name', sa.String(length=50), nullable=True),
    sa.Column('camera_ip', sa.String(length=50), nullable=True),
    sa.Column('camera_position', sa.String(length=50), nullable=True),
    sa.Column('rtsp_address', sa.String(length=50), nullable=True),
    sa.Column('distinguish_wide', sa.String(length=50), nullable=True),
    sa.Column('check_space', sa.String(length=50), nullable=True),
    sa.Column('scene_at_degree', sa.String(length=50), nullable=True),
    sa.Column('move_check_wide', sa.String(length=50), nullable=True),
    sa.Column('equipment_state', sa.String(length=50), nullable=True),
    sa.Column('unique_server_id', sa.String(length=50), nullable=False),
    sa.Column('camera_state', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['unique_server_id'], ['tb_server.unique_server_id'], ),
    sa.PrimaryKeyConstraint('unique_camera_id')
    )
    op.create_table('tb_role_limit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('lid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lid'], ['tb_limit.lid'], ),
    sa.ForeignKeyConstraint(['rid'], ['tb_role.rid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rid'], ['tb_role.rid'], ),
    sa.ForeignKeyConstraint(['uid'], ['tb_user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_alarm_info',
    sa.Column('alarm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alarm_content', sa.String(length=128), nullable=True),
    sa.Column('alarm_time', sa.DateTime(), nullable=True),
    sa.Column('face_recognition', sa.String(length=50), nullable=True),
    sa.Column('image', sa.TEXT(), nullable=True),
    sa.Column('unique_camera_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['unique_camera_id'], ['tb_camera.unique_camera_id'], ),
    sa.PrimaryKeyConstraint('alarm_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_alarm_info')
    op.drop_table('tb_user_role')
    op.drop_table('tb_role_limit')
    op.drop_table('tb_camera')
    op.drop_table('tb_user')
    op.drop_table('tb_server')
    op.drop_table('tb_role')
    op.drop_table('tb_limit')
    # ### end Alembic commands ###
